<?xml version="1.0"?>
<!DOCTYPE moduleset SYSTEM "moduleset.dtd">
<?xml-stylesheet type="text/xsl" href="moduleset.xsl"?>
<moduleset>
<repository type="tarball" name="sourceforge" href="https://downloads.sourceforge.net/project/" />
<repository type="tarball" name="gnome" href="http://ftp.gnome.org/pub/GNOME/sources/" />
<include href="http://github.com/jralls/gtk-osx-build/raw/master/modulesets-stable/gtk-osx.modules"/>
<autotools id="etl">
<branch repo="sourceforge" module="/synfig/ETL/0.04.13/ETL-0.04.13.tar.gz" version="0.04.13" />
</autotools>
<autotools id="libsigc++">
<branch repo="gnome" module="libsigc++/2.2/libsigc++-2.2.8.tar.bz2" version="2.2.8" />
</autotools>
<autotools id="libxml++">
<branch repo="gnome" module="libxml++/2.33/libxml++-2.33.2.tar.gz" version="2.33.2" />
<dependencies>
<dep package="glibmm" />
</dependencies>
</autotools>
<autotools id="synfig">
<branch repo="sourceforge" href="/synfig/synfig/0.62.02/synfig-0.62.02.tar.gz" version="0.62.02" />
<dependencies>
<dep package="etl" />
<dep package="libsigc++" />
<dep package="libxml++" />
<dep package="gettext" />
</dependencies>
</autotools>
<autotools id="synfigstudio">
<branch repo="sourceforge" href="synfigstudio/0.62.02/synfigstudio-0.62.02.tar.gz" version="0.62.02" />
<dep package="etl" />
<dep package="libsigc++" />
<dep package="gtkmm" />
<dep package="gtk" />
<dep package="glibmm" />
<dep package="gettext" />
</dependencies>
</autotools>
</moduleset>